---
title: "README"
author: "Andy Hebert"
date: "6/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting and Cleaning Data Week 4 project - README
 this will describe what actions the R script run_analysis will perform on files from the
 UCI HAR Dataset see code book for description and source of this dataset and variables used in analysis
 

### run_analysis.R

this script will read in data from multiple file, appropriately label all variables, merge/concatenate file as needed and ultimately summarize certain columns by generating means for these columns by activity and subject

Intended to be used in conjuction wth the R script.
1. read in features data from features.txt
      contains 561 observations
      2 variables - features.key and features
            features are the different measurments taken and will act as column names for other data
2. read in activities data from activities_label.txt
      contains 6 observations 
      2 variables
            activities_key
            activity - description of various activities during which measurments were performed 
3. read in subject id's for training and test data sets (subject_train.txtx and subject_test.txt)
      label column as subject_key
4. read in x_test and x_train files
      apply column names from features 
5. read in y_test and y_train files
      rename col header to activity_key
6. all_test - combine cols from y_test (activity), subject_test, and x_test (measurment) cind()
       
7. all_train - combine cols from y_train (activity), subject_train and x_train

8. all_data - concatenate from all_test and all_train rbind()

9. create a list of logicals of which columns are relevent to the final results

10. selected_data - use this list to create a data.frame of just the cols we are interested in.

11. labeled_selected_data will use activity_key to merge activity description with selected data
      this should be saved until all other merges etc are completed as it will reorder the data
12. Data_Results - uses the aggregate function to generate means on all mean() and std() columns by activity and then by subject
13. write out final results to a file